name: kokoitta_app
description: "写真からつくるおでかけ地図"
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
